### ISSUE TITLE
BUG - Editor Title showing as 'Background' on content edit

### ISSUE THREAD

**Issue by DuncanChittick** [pootlepress/pootle-page-builder#1]
![screen shot 2015-07-02 at 09 51 56](https://cloud.githubusercontent.com/assets/11769538/8473272/205f2de2-20a0-11e5-9d45-62a52a0cf0e3.png)

**Comment by nickburne** [comment]
Over to you Shramee. Should say 'Editor'

**Comment by shramee** [comment]
Kindly check it out ;)

**Comment by nickburne** [comment]
Ok - fixed.
