### ISSUE TITLE
Color pickers not reflecting color

### ISSUE THREAD

**Issue by shramee** [pootlepress/pootle-page-builder#13]
In add content panel the color pickers in style tabs don't show the colors after being set.

Replication:
1. Go to add content panel for any widget.
2. Set colors.
3. Hit save.
4. Open the add content panel for the same widget.
5. OMG! WHERE ARE MY PRECISELY SET COLORS!!!
6. Click the picker and, Phew! the code is their in the input box.
7. Save it and Update it. Works fine on the front end...

So we just need to trigger a change event to make them appear in picker.

**Comment by nickburne** [comment]
Ok - please fix 

But don't call them widgets anymore ; )

**Comment by shramee** [comment]
Hmmm... It makes no sense...
Kindly check it out ;)

**Comment by nickburne** [comment]
Cool
