### ISSUE TITLE
Add subscribe option on activation (to campaign monitor)

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#132]
![screen shot 2016-03-22 at 15 03 15](https://cloud.githubusercontent.com/assets/3070779/13956116/4d8c7468-f03f-11e5-9528-ed9c4450dcbd.png)

**Comment by shramee** [comment]
Freemius handles this for us now :)

Lemme know if we wanna do to subscribe to pp.com :wink:

**Comment by jamiemarsland** [comment]
Yes we need to link this to campaign monitor subscription
