### ISSUE TITLE
Page builder reload issue 

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#14]
When you update a pagebuilder page now, you see the 'get started with pagebuilder text' before the page builder rows then load in. Not a great experience. 

Here's a link to a video. Tested on 2 sites and it's an issue. 

https://vimeo.com/132741285

**Comment by shramee** [comment]
Lemme know how it works 4 ya ;)

**Comment by jamiemarsland** [comment]
Can't add pages now :(

Can you test before pushing next time pls

**Comment by shramee** [comment]
Lemme know if it's all right now...

**Comment by jamiemarsland** [comment]
Great :)
