### ISSUE TITLE
Image sizes differ in content blocks

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#16]
Add a row of 4 columns. Put an image in the first content block. Then duplicate that content block to the 3 remaining columns. See screenshot of the issue below. The middle 2 pics are different sizes to the ones in the outer columns
![screen shot 2015-07-08 at 12 19 32](https://cloud.githubusercontent.com/assets/3070779/8569073/a896a788-256b-11e5-81ce-970065e580a2.png)

**Comment by jamiemarsland** [comment]
We get the same issue with 3 columns

**Comment by nickburne** [comment]
New gutter solution with drop down of:

None
Small
Medium
Large

Using %s

**Comment by shramee** [comment]
Kindly check it out.
