### ISSUE TITLE
HIGH - page builder removes WooCommerce 'Products' nav item from main WordPress nav

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#19]
Hi Shramee,

This is an important one. When ppb is activated it removes the 'Products' item from the main WP navigation when WooCommerce is installed.

**Comment by nickburne** [comment]
Also - I think Page Builder should always appear under Pages in the main nav.

**Comment by shramee** [comment]
Kindly check it out ;)

**Comment by nickburne** [comment]
Done! Nice.
