### ISSUE TITLE
Scrolling not working on mobile browsers

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#23]
Scrolling of pages doesn't work on mobile browsers. 

Tested on iphone - safari and chrome - doesn't work

**Comment by nickburne** [comment]
Parallax has been turned off for mobile devices. Nick to test.

**Comment by nickburne** [comment]
This is still not working. This site is now updated with 0.2.1

http://pagebuilder.thisistap.com/para/

Can you see it on an iphone?

**Comment by jamiemarsland** [comment]
Confirmed not working :(

**Comment by nickburne** [comment]
Damn. By passed our testing process. I know why.

**Comment by shramee** [comment]
This removes parallax effect on chrome iPhone simulation...

**Comment by nickburne** [comment]
Can you test on a real iPhone??

**Comment by DuncanChittick** [comment]
This is working on iOS 9
