### ISSUE TITLE
Support for PHP 5.2.4

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#24]
Need to do a thorough test on PHP 5.2.4 and fix any issues.

**Comment by shramee** [comment]
Seems good to me...

**Comment by shramee** [comment]
Will do a last (thorough) test tomorrow...

**Comment by shramee** [comment]
Yep, all good now.

**Comment by DuncanChittick** [comment]
Not sure how to test this one @nickburne ?

**Comment by nickburne** [comment]
@DuncanChittick you need to research this. Hopefully you can find a tool to replicate a local environment of 5.2.4 (maybe it's a feature of ampps?)

**Comment by nickburne** [comment]
@DuncanChittick don't think we can test this - will have to be something @shramee does for us.

So closing.
