### ISSUE TITLE
background video not autoplaying in safari on mac

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#26]

**Comment by nickburne** [comment]
Works fine on storefront but not on twenty fifteen.

**Comment by shramee** [comment]
Not able to replicate...
Video is autoplaying for me -
![screen shot 2015-07-15 at 1 15 53 pm](https://cloud.githubusercontent.com/assets/11048263/8693325/f80a7636-2af3-11e5-9ce3-7bccb84229c8.png)
on macbook air Yosemite

**Comment by DuncanChittick** [comment]
Also autoplaying for me? @nickburne any more info?

**Comment by nickburne** [comment]
If you guys have both tested it and it's fine, then I think that's good enough. It will have to pass testing again anyway... Closing..
