### ISSUE TITLE
Equal content block height in row

### ISSUE THREAD

**Issue by shramee** [pootlepress/pootle-page-builder#261]
Add an option to make all content blocks in a row of same height.

**Comment by jamiemarsland** [comment]
Almost there - a couple of issues

1) I think it should be checked by default
2) If you add padding then text comes out of content area - see screenshot (in the example below i have added 50px padding to each content area)
3) Lets change help text slightly .from Does not work in live editor to.....Will not preview in live editor but it will work once published. 

![screen shot 2016-07-15 at 17 51 05](https://cloud.githubusercontent.com/assets/3070779/16882025/d6a59372-4ab4-11e6-9985-fa9a7a63eb1c.png)
