### ISSUE TITLE
add media not working first time

### ISSUE THREAD

**Issue by DuncanChittick** [pootlepress/pootle-page-builder#27]
When selecting an image from the 'add media' panel within the content block editor the media takes two attempts to load successfully.

**Comment by nickburne** [comment]
This is because the first time the mouse cursor is not in the editor

**Comment by nickburne** [comment]
The default wordpress editor deals with this somehow. @shramee can you take a look?

**Comment by shramee** [comment]
Lemme konw how it wokrs for ya...

**Comment by DuncanChittick** [comment]
This now works great in Safari, Firefox and Chrome.
