### ISSUE TITLE
Plugin conflict

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#29]
Just got a report that this is conflicting:
https://wordpress.org/plugins/seriously-simple-podcasting/

@DuncanChittick - can you test first and then assign to shramee to take a look. Please note - it's something the plugin developer may have to fix - not us.

**Comment by DuncanChittick** [comment]
Yep - @shramee lets see whats wrong here.

**Comment by nickburne** [comment]
@shramee - you need to assign this to @DuncanChittick

**Comment by DuncanChittick** [comment]
Yes @shramee fix did work. Closing
