### ISSUE TITLE
MODULES - USERS NEEDS FEEDBACK ON WHERE THEY ARE DROPPING MODULES

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#302]
We need to give users greater precision over where they are dropping modules within content areas. 

At the moment the content area turns red which is great, however users have no idea where specifically within the content area the module will be dropped. 

So users need some feedback before they drop

See video on the problem at the mo

https://www.dropbox.com/s/7uc9todlztls75y/dropping%20buttons.mp4?dl=0

**Comment by shramee** [comment]
Don't need this anymore...
