### ISSUE TITLE
MODULES - Interface for setting Unsplash row backgrounds

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#304]
I think it would make more sense to have an extra Unsplash tab on this screen (as opposed to having an unsplash button on previous screen)

So the tabs would be upload files | media library | Unsplash images

Clicking on unsplash would launch search screen

![screen shot 2016-08-04 at 18 40 36](https://cloud.githubusercontent.com/assets/3070779/17412340/25030526-5a74-11e6-9d6d-946d82eb4e74.png)

**Comment by shramee** [comment]
As discussed on slack...
Let's add a new search input besides image selection for row style panel image controls...
