### ISSUE TITLE
duplicate button not working in firefox in 0.2.1

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#31]

**Comment by DuncanChittick** [comment]
I'm getting the same issue in safari

**Comment by nickburne** [comment]
In which version?

**Comment by DuncanChittick** [comment]
8.0.6

**Comment by nickburne** [comment]
sorry - i meant of ppb

**Comment by DuncanChittick** [comment]
0.2.2 pre release

**Comment by nickburne** [comment]
Working for me in firefox in 0.2.2

**Comment by DuncanChittick** [comment]
My safari wasnt up to date - its now on 8.0.6 (as I thought before) and the duplicate is working.

**Comment by nickburne** [comment]
ok closing
