### ISSUE TITLE
MODULES - Change default module order in pseudo customizer

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#320]
Let's have this order

Hero
Slider
Unsplash
Pootle button
Blog posts
WooCommerce
Ninja forms
Meta slider

**Comment by shramee** [comment]
- [x]  Hero
- [x]  Image
- [x]  Pootle Slider
- [x]  Photo Gallery
- [x]  Unsplash
- [x]  Pootle button
- [x]  Blog posts
- [x]  WooCommerce
- [x]  Ninja forms
- [x]  Meta slider

**Comment by jamiemarsland** [comment]
The order has changed again - let's change back to what we have outlined in this ticket

**Comment by jamiemarsland** [comment]
Also Unsplash is called Unsplash Image (which is correct)
