### ISSUE TITLE
editor in firefox

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#33]
The visual tab and text tab in the pootle page builder have different heights.

Visual tab is too long, and text tab is too short.

<img width="1051" alt="screenshot 2015-07-16 14 40 16" src="https://cloud.githubusercontent.com/assets/3784875/8724840/b29563ba-2bc8-11e5-918f-5240f28a28bb.png">

**Comment by DuncanChittick** [comment]
Lets do this as discussed - Dynamic height using js after opening.

**Comment by shramee** [comment]
Lemme know how it works for ya ;)

**Comment by DuncanChittick** [comment]
This works nicely for me, closing.
