### ISSUE TITLE
Match height works sometimes but not others

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#336]
We have an issue but im struggling to replicate

See screenshot. Match height is ticked. 

![screen shot 2016-08-09 at 19 03 15](https://cloud.githubusercontent.com/assets/3070779/17527639/12fe351e-5e64-11e6-8a08-70fb759674c2.png)

**Comment by shramee** [comment]
Do we have this live somewhere so that I can inspect? 😅

**Comment by jamiemarsland** [comment]
Still not working for me
