### ISSUE TITLE
row background video not working properly on iphone

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#34]
It's not a background video. It has a play button with sound. 

It's suppose to be a backgtround video (no play button, no sound)

**Comment by shramee** [comment]
https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html suggests autoplay is disabled on iOS devices... :disappointed:

**Comment by shramee** [comment]
![image](https://cloud.githubusercontent.com/assets/11048263/8746645/177f3f9a-2ca9-11e5-8345-8d36cbdb5fc1.png)
This translucent image is added for each video...

**Comment by nickburne** [comment]
Ok, here are my suggestions for this for now:
1. Add a tool tip to Background Video option that says "Background videos autoplay & therefore only work on desktop browsers"
2. Change the tool tip for 'Responsive image' to "Select an image to display instead of the background video for mobile devices"

Now, here's the main change. Users are required to complete both these fields for background videos to work. So the responsive image is mandatory if a user has uploaded a video. Therefore there needs to be some kind of message if the user uploads a video and doesn't upload a responsive image.

**Comment by shramee** [comment]
Lemme know how it works 4 ya, Lemme know about the massage ;)

**Comment by nickburne** [comment]
Ok it's looking pretty good.
1. Question - is it possible to trigger the message when I click 'Done' without a background image? At the moment it is triggered as soon as I upload a background video before i have even had a chance of uploading the background image.
2. Please change the error message to "Please select an image to display instead of the background video for mobile devices"

**Comment by shramee** [comment]
Lemme know how it works for ya

**Comment by DuncanChittick** [comment]
Looks ok - will test in more detail during pre release testing.
