### ISSUE TITLE
Pootle button - icons not scaling properly

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#342]
See screenshot....if you increase the size of the button the icons aren't getting bigger.

![screen shot 2016-08-10 at 12 14 03](https://cloud.githubusercontent.com/assets/3070779/17551800/0dfc8a6c-5ef4-11e6-98c8-77c4072c2edf.png)

**Comment by shramee** [comment]
Not able to reproduce on storefront...
Which theme are we using?
Might be happening on particular themes only...

**Comment by jamiemarsland** [comment]
testing on 18 tags on pootle-band.co.uk
