### ISSUE TITLE
parallax disabled for mobile but background image size setting not being respected

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#36]
when i set a background image to a row and give it the parallax option it works on desktop but not on mobile (my iphone) (which is correct)

But on mobile the image does not respect the background image size option (in my test it is 'cover'). 

So for example if I then deactivate the parallax option and look at my iphone again, the image changes to the cover setting correctly. It should have the correct background image size option in mobile even if parallax is being blocked for mobile.

**Comment by shramee** [comment]
Lemme know how it works 4 ya ;)

**Comment by DuncanChittick** [comment]
This looks to now be working: 

I get this on chrome (with parallax effect):
<img width="1392" alt="screen shot 2015-07-17 at 10 51 38" src="https://cloud.githubusercontent.com/assets/11769538/8744778/dfdec74a-2c71-11e5-94a8-6942218adf18.png">
http://duncan.thisistap.com/test/

I get this on iOS:

![Uploading IMG_3339.PNG…]()
