### ISSUE TITLE
ppb page content lost when no page title 

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#37]
On certain themes, if you create a page with page builder with lots of rows/columns/content etc and then publish the page without a page title, you loose all your content as it goes back to the default editor.

The theme I found this happening on is a popular free one that can be found through worpdress called Customizr

https://wordpress.org/themes/customizr/

I think it's happening on other themes though.

**Comment by shramee** [comment]
Hmm...
WP checked if title, content and excerpt are all empty and are all supported the post is considered empty...
**Customizr added excerpt support to pages!!**, There could be many themes doing this.
Consequently they were taken as empty and not saved...
We now use `wp_insert_post_empty_content` to explicitly set post as **not empty** if panels got at least 1 row...

**Comment by DuncanChittick** [comment]
This also works with 3 themes I have tried. Well done @shramee
