### ISSUE TITLE
Features with icons module

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#383]
A pro module to show features with a choice of font awesome icons above

![screen shot 2016-08-26 at 21 29 50](https://cloud.githubusercontent.com/assets/3070779/18019492/44c2f954-6bd4-11e6-92f8-b68f459a6efc.png)

**Comment by jamiemarsland** [comment]
This is great , just one thing

1) At the moment there is no way to re-edit the icon once it's inserted. It would be great if this could work like pootle button, double clicking re-opens the icon editor

**Comment by jamiemarsland** [comment]
Almost there, but ..

1) now the size slider keeps getting stuck with my mouse so as i move my mouse anywhere the slider moves. https://www.dropbox.com/s/7axe8kyutspns7j/slider%20issue.mp4?dl=0

2) Also i liked it when we have a numeric to show the icon image after dragging the slider - this is needed so users can get consistent icons

3) There's no way to delete an icon at the moment

**Comment by jamiemarsland** [comment]
A couple of issues

1) The workflow feels clunky to me - can we use the same workflow that we have when selecting icons, setting the size and removing icons in pootle button, this seems much more friendly and intuitive https://www.dropbox.com/s/ulop4pnpsa9pg9i/icon%20selection%20workflow.mp4?dl=0. This way we can also remove the big grey 'remove icon button' on the modal.

2) Changing the color is not being saved after publish https://www.dropbox.com/s/y9sfar5ia13tnbv/icon%20color%20issue.mp4?dl=0

**Comment by jamiemarsland** [comment]
Fantastic !

How about we add a field so that users can link the icons?

**Comment by jamiemarsland** [comment]
Links are being stripped when you re-edit

**Comment by jamiemarsland** [comment]
If you re-edit the color the icon aligns left (it should be centered)

**Comment by jamiemarsland** [comment]
We've still got bugs

1) if you put a link in, then choose the icon , then insert , the icon doesn't insert
2) links getting stripped from icons

**Comment by jamiemarsland** [comment]
1) if you put a link in, then choose the icon , then insert , the icon doesn't insert
2) links getting stripped from icons

**Comment by shramee** [comment]
Not able to reproduce is it available online?
