### ISSUE TITLE
Opacity wording unclear

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#4]
Possibly use transparent/solid

**Comment by nickburne** [comment]
Ok - so for this we need to make some changes:
1. We need to change the 'Overlay color opacity' to 'Overlay color transparency' (the reverse)
2. The slider needs to start at 50%
3. We need to have a preview of the row background image somewhere after the user uploads the image. Let's slack about this.

**Comment by shramee** [comment]
1 and 2 done

**Comment by DuncanChittick** [comment]
1 and 2 working fine.
