### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#402]
Some customers are reporting very slow page loading times

"I've just looked at my home page within Pootlepress page builder and have noticed that over 15,000 words of copy are showing up. Is there any way you can clear that from your end as I only have about 200 words of copy on there now. This means that page builder is storing all of the changes I make which is slowing down this page. Can you clear it on your end? Hostgator my host says you are the only one who can do that? Please advise. Thanks. Kathryn'

**Comment by shramee** [comment]
Continues in #403...
