### ISSUE TITLE
if you use page builder a 2nd time but haven't saved a page

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#41]
It points an arrow to the existing layouts button, which is not there...

**Comment by nickburne** [comment]
The arrow and help text that points to the existing layouts button should only trigger if a page builder page has been saved and the existing layouts button is present.

**Comment by shramee** [comment]
Lemme know how it works for ya

**Comment by DuncanChittick** [comment]
Yep - working now.
