### ISSUE TITLE
Pootle Pagebuilder stripping words

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#428]
I've had a few reports of this, and now i have an example that i've managed to replicate

the moves that go along with that kind of music

becomes....

the moves that go that kind of music

so it's stripping out 'along with'

**Comment by shramee** [comment]
Ragadjust is causing this.... Let's remove it...

**Comment by jamiemarsland** [comment]
I think this is now fixed?
