### ISSUE TITLE
Styling fields should be sortable

### ISSUE THREAD

**Issue by shramee** [pootlepress/pootle-page-builder#44]
Settings in row/content styling fields can be added using hook `pootlepb_row_style_attributes` and `pootlepb_content_block_fields` however these are not prioritized...

For example if I add a field to background tab of row styling panel it's gon appear at the very end I can't have it to appear, say, right after bg image field...

**Comment by nickburne** [comment]
I agree - can you do this please?

**Comment by shramee** [comment]
Aye :)

**Comment by shramee** [comment]
Done
