### ISSUE TITLE
$currentPanel.data('dialog') not available

### ISSUE THREAD

**Issue by shramee** [pootlepress/pootle-page-builder#45]
$currentPanel.data('dialog') set to null before triggering `pootlepb_admin_content_block_title` event for smart titles,
Consequently newly set properties ain't accessible by **smart title** events handlers...

**Comment by shramee** [comment]
This is done... To test smart titles in ppb-portfolio-addon

**Comment by nickburne** [comment]
Assign to me?

**Comment by shramee** [comment]
Nope, I just gotta check if smart titles are working like a charm again...
They weren't after we implemented our awesome new editor ;)

**Comment by shramee** [comment]
Works.

**Comment by nickburne** [comment]
When using portfolio add on and making a content block a portfolio item it doesn't update the smart title until the page is saved.

This is on master branch.

**Comment by shramee** [comment]
Sorry, didn't mention that but all new stuff is on ppbDialog branch...

**Comment by nickburne** [comment]
Ok - working
