### ISSUE TITLE
Enable background color of content area to accept RGBA (for transparency)

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#50]
Currently you can't set a semi transparent background for content areas. So achieving the below is not possible. 

![screen shot 2015-07-29 at 19 54 20](https://cloud.githubusercontent.com/assets/3070779/8989729/daa95e38-36e5-11e5-8ffd-0b6a827dcece.png)

**Comment by jamiemarsland** [comment]
ignore this - it does already work

**Comment by nickburne** [comment]
Reopening as I am trying to get away from rgba use as it's pretty technical.

Do we need a transeparency slider?

**Comment by jamiemarsland** [comment]
A slider would be fab !

**Comment by nickburne** [comment]
Added a new ticket
