### ISSUE TITLE
Pro module - Business Pro pack

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#512]
This will be installed the same way as WooCommerce Builder (i.e from wp.org) but only for Pro customers

So include the following modules

1) Testimonials
2) Number counter 
3) Google map
4) Tabs
5) Social icons
6) Accordian

**Comment by shramee** [comment]
- [x] 1) Module - Testimonials
- [x] 2) Module - Number counter 
- [x] 3) Setting - Google map
- [ ] 4) UI - Tabs
- [x] 5) ~~Social icons~~ Add inline option in icon module
- [ ] 6) UI - Accordion
