### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by sollutto** [pootlepress/pootle-page-builder#517]
Hi,

I am new here, have a little experience with WP etc.
I have a question
This pootle page builder, is this the pro version?
Because i get a screen with the text: 

Thanks for purchasing Pootle Pagebuilder! To get started, please enter your license key:

ty for the help
goodbye

**Comment by sollutto** [comment]
Why are you not responding
or someone else

**Comment by shramee** [comment]
Hi @sollutto 🙂 

This is not intended to be use by the end users, this is for development only, it's here for forking and contributing new features. For using it on your site download it from https://wordpress.org/plugins/pootle-page-builder/

Cheers
