### ISSUE TITLE
Strange hover effect in editor when Tabs Manager active

### ISSUE THREAD

**Issue by DuncanChittick** [pootlepress/pootle-page-builder#54]
<img width="395" alt="screen shot 2015-07-31 at 14 30 59" src="https://cloud.githubusercontent.com/assets/11769538/9008256/e0594e6e-3790-11e5-9a9e-c4ab6024e6d6.png">

With YITH WooCommerce Tabs Manager installed the editor styling has gone wrong. See Screenshot.

**Comment by shramee** [comment]
Lemme know if it's all righty now.

**Comment by nickburne** [comment]
Yep - better now.
