### ISSUE TITLE
Add new options - add and remove columns in row

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#55]
In the row icons next to the up/down icon, let's try 2 new icons
1. https://developer.wordpress.org/resource/dashicons/#plus

This adds a column (e.g. changing the row from 4 columns to 5 columns)
1. https://developer.wordpress.org/resource/dashicons/#minus

This would remove the most right hand empty column. If there are no empty columns it would give a warning in a diagloue box that says "You can only remove an empty column, please move or delete content from the column you wish to remove."

**Comment by shramee** [comment]
This is gonna be a delicious addition...

**Comment by shramee** [comment]
Lemme know how it works 4 ya ;)

**Comment by nickburne** [comment]
I really like this!

**Comment by shramee** [comment]
There's a bug...
The setting of row are lost when tryna add or remove columns.

**Comment by nickburne** [comment]
Ok - can you fix?

Also - new drag area is good, but could the area that is 'enabled' be larger (on the top)

Thanks! N

**Comment by shramee** [comment]
Fixed, Kindly check it out ;)
