### ISSUE TITLE
Move styling options for Rows and Content Blocks into pseudo customizer

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#554]
It would be better if styling options could be moved into a pseudo customizer. This would achieve a few things

1) Live previews of any changes being made - so users would see real time (eg upload background image to row) 

2) Keep content separate from styles so for content Blocks - the pencil icon would just give users the ability to edit content

3) To access the panel users would click on the row or content icons (or a better way if we can think of one)

**Comment by shramee** [comment]
Changes here ;)

https://github.com/pootlepress/pootle-page-builder/tree/live-preview
