### ISSUE TITLE
Remove updown arrow icon and make whole area drag enabled

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#57]

**Comment by shramee** [comment]
Done for the row, now the whole row icons (.controls) region is draggable (handle for sorting rows).
Lemme know how it works for ya.

**Comment by nickburne** [comment]
Also - new drag area is good, but could the area that is 'enabled' be larger (on the top)

**Comment by shramee** [comment]
Yep, Lemme know how it works for ya.

**Comment by nickburne** [comment]
Loving it!
