### ISSUE TITLE
Fix Style Panel fonts and sizes so that themes don't overide them

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#582]

**Comment by jamiemarsland** [comment]
This isn't working - theme styles still seem to overide  whats shown in our new customizer

![screen shot 2017-04-20 at 17 49 52](https://cloud.githubusercontent.com/assets/3070779/25242511/d7cc56aa-25f1-11e7-8f0e-cc08c2201f62.png)

**Comment by jamiemarsland** [comment]
It's still inheriting Heading Color (see screenshot)

![screen shot 2017-04-21 at 12 02 29](https://cloud.githubusercontent.com/assets/3070779/25274915/7d9b7e9c-268a-11e7-881b-6da81493baf5.png)

**Comment by shramee** [comment]
Ohh, lemme add rule for color too 😅
