### ISSUE TITLE
Image selection button

### ISSUE THREAD

**Issue by shramee** [pootlepress/pootle-page-builder#6]
**Select image** buttons in **Row Visual Style** Panel opens multiple instances of Image selection dialog _(equal to the times *_Row Visual Style*\* Panel is opened)*.
1. Go to any page using PPB
2. Open **Row Visual Style** Panel.
3. Close it.
4. Repeat 2 and 3, 2 times.
5. Opened Row Visual Style 3 times
6. Open **Row Visual Style** Panel again the 4th time.
7. Go to Background > Choose BG image > In Background Image, Click Select image > Choose Image > Hit Set as BG image. OMGWTFBBQ? Shows The button disabled!
8. Choose image and Click Set as BG image again _( need to do it as many times **Row Visual Style** Panel was opened )_.

**Comment by shramee** [comment]
Kindly check it out...

**Comment by nickburne** [comment]
Ok fixed, but then I never saw it in the first place!
