### ISSUE TITLE
Responsive line breaks - words being split

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#60]
On a phone words are breaking

See pootlepress.com for an example

It would be good if words could hypenate or we have line breaks.

**Comment by nickburne** [comment]
Hey Shramee - Jamie is right. Check out pootlepress.com on the iphone on http://ipadpeek.com/

Word are breaking across lines. Is there anything we can do about this? 

Does it happen in the default editor??

**Comment by jamiemarsland** [comment]
I found this article which might help http://danielmall.com/articles/responsive-line-breaks/

**Comment by shramee** [comment]
Thanks Jamie :smile: ,
You are right methods for automatic hyphenation ain't feasible yet... author must add responsive line breaks or word break wherever required...
`hyphens` css property is not supported by major browsers yet (not even chrome), though it is supported in ff, but I couldn't get it to work and js methods are pretty expensive...

> Hyphenator.js and the hyphenation patterns are quite large. A good compression and caching is vital.

What we can do is, add `&shy;` to very long words where we would like to get them hyphenated from... or add a `<wbr>` tag
![image](https://cloud.githubusercontent.com/assets/11048263/9191947/6977867a-4024-11e5-8898-fbd062efd8a5.png)

 And added `<br class='rwd'>` for responsive line breaks that would work at resolutions < 769px.

Lemme know if this helps addressing the issue...
