### ISSUE TITLE
Opacity dialogue cut off

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#61]
When setting the opacity for an image for a row - the color picker is cut off at the bottom and you can\t scroll down. See screenshot. 

![screen shot 2015-08-08 at 05 24 34](https://cloud.githubusercontent.com/assets/3070779/9149066/f6caf5e6-3d8d-11e5-8efe-9eebee709352.png)

**Comment by shramee** [comment]
Hi

**Comment by shramee** [comment]
Kindly check it out and lemme know if issue persists.
Thanks :smile:

**Comment by nickburne** [comment]
Fixed.
