### ISSUE TITLE
Live Templates - Save Row

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#612]
Maybe we add an extra tab here - that says 'save row to PootleCloud'

t feels like it should be at this level

And it there users can 

1) Login (if not logged in)
2) Save row
3) Manage templates
4) Log out of PootleCloud

![screen shot 2017-06-30 at 17 10 57](https://user-images.githubusercontent.com/3070779/27744368-2ba13a64-5db7-11e7-9484-256b7432f048.png)

**Comment by shramee** [comment]
This should be in Pootle Cloud repo 😉 
pootlepress/pootle-cloud#1
