### ISSUE TITLE
Live Templates Branch (phase 2) - Would it be possible to work with other modules e.g posts / testimonials?

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#618]
So users could create a row - bring the posts module into it - make their changes and save as a template  - then reuse that template?

**Comment by shramee** [comment]
Aye, it should be working right now 😄  Coz we grab all content data as well 😉

**Comment by jamiemarsland** [comment]
This doesn't seem to work for me - i tested creating a slider and then saving the row as a template, but it doesn't show when reusing?
