### ISSUE TITLE
Adding lots of text to editor breaks scroll (and done button)

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#62]
If you add lots of text to the editor then you can no longer scroll up (or down)

Also the 'Done' button starts floating up the right side of the screen, 

See screenshot

![screen shot 2015-08-08 at 07 12 18](https://cloud.githubusercontent.com/assets/3070779/9149334/ff0d27b0-3d9c-11e5-8a66-ba4d01bea8ed.png)

**Comment by shramee** [comment]
Lemme konw if it is fixed 4 ya :wink:

**Comment by nickburne** [comment]
Fixed!
