### ISSUE TITLE
Flex Branch - remove help text for CONTENT BLOCK BACKGROUND IMAGE

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#637]
We don't need the helptext or ? now we've put the button back

![screen shot 2017-07-11 at 20 47 43](https://user-images.githubusercontent.com/3070779/28087430-589523d4-667a-11e7-8acc-f95ca1224523.png)

**Comment by shramee** [comment]
Aah, right. Oops 😅
