### ISSUE TITLE
Get the add-ons page ready

### ISSUE THREAD

**Issue by shramee** [pootlepress/pootle-page-builder#64]
Get the add-ons page ready... We'd probably need get it from pp.com for this but for now show all active addons with content from plugin...

**Comment by shramee** [comment]
This is what addons page will looks like...
Right now getting info from wp plugin header comment.

![image](https://cloud.githubusercontent.com/assets/11048263/9220659/c78135bc-4101-11e5-8fdd-29f3042cc70a.png)

**Comment by shramee** [comment]
After footer styles...
![image](https://cloud.githubusercontent.com/assets/11048263/9220778/81a686ea-4102-11e5-992b-50c8f3966a6f.png)

**Comment by nickburne** [comment]
Great
