### ISSUE TITLE
Post builder

### ISSUE THREAD

**Issue by shramee** [pootlepress/pootle-page-builder#650]
No way to return to new posts after click `Previous` posts link

**Comment by sharpsagen** [comment]
Client is using crap GoDaddy hosting.  Is there anything I can do?

**Comment by jamiemarsland** [comment]
This seems to work ok  in my tests, i'll try to replicate on another site today

**Comment by sharpsagen** [comment]
Hi,

Client noticed that we still have an issue with blog posts.  

http://www.drquattro.com/ <http://www.drquattro.com/>

but previous doesn’t allow you to view old/newer

http://www.drquattro.com/page/2/ <http://www.drquattro.com/page/2/>


Melody Sharp
831-685-8318

http://www.melodysharp.com
http://santa-cruz-web-design.com
