### ISSUE TITLE
Row opacity settings defaulting to 50% and cannot be reduced

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#66]
See screenshot. 

I'm not really sure why they start at 50% either?

![screen shot 2015-08-13 at 10 59 56](https://cloud.githubusercontent.com/assets/3070779/9247385/8e99592e-41aa-11e5-816b-1c7eda52c8de.png)

**Comment by shramee** [comment]
Lemme know how it works for ya!

**Comment by jamiemarsland** [comment]
ok fixed :)
