### ISSUE TITLE
Custom post type builder

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#668]
Some inspiration - be great to do this for woobuilder as well

https://siteorigin.com/downloads/premium/

**Comment by beingtree** [comment]
in the meantime, if you need pootle pagebuilder functionality on your custom post types, you can do something like this in your (child) theme's functions.php

`function theme_name_add_ppb_press_post_type( $post_types ) {

		$post_types[] = 'custom_post_type_name';

		return $post_types;

	}

add_filter( 'pootlepb_builder_post_types', 'theme_name_add_ppb_press_post_type');
`
