### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#8]
See screenshot - getting black screen when trying to add content

tested on 2 sites

![screen shot 2015-07-06 at 15 00 10](https://cloud.githubusercontent.com/assets/3070779/8523910/e20ff32a-23ef-11e5-84cf-846e4ac11d0d.png)

**Comment by nickburne** [comment]
Hey @shramee - assume this is because you are scruiting?

**Comment by nickburne** [comment]
Working fine now...
