### ISSUE TITLE
Multiple delete of rows doesn't work when all rows are deleted in a page

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#84]
If you delete all the rows eg i have 5 rows and i delete them all in one go and then hit save. They don't all get deleted.

**Comment by nickburne** [comment]
Can you fix Shramee?

**Comment by shramee** [comment]
Hmm...
We were skipping the save_post method if no rows are set...
Now we delete the the meta if no rows are set...
And it solves the prob ;)
Lemme know...
