### ISSUE TITLE
Improve design

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#85]
<img width="747" alt="screenshot 2015-08-25 15 56 59" src="https://cloud.githubusercontent.com/assets/3784875/9470421/d2d83a04-4b43-11e5-92a0-cc67e9d2a78d.png">

**Comment by nickburne** [comment]
The addons should be more like plugins when you add a plugin. More padding and wider too...

**Comment by shramee** [comment]
Aye... Increased the margin, padding and width like app new plugin page items...
However we could make it more informative...
Like showing the current version on pp.com and comparing it with version user got installed to encourage getting it activated ( like we wanted in the beginning ), and maybe show compatibility with wp version too...
