### ISSUE TITLE
Fatal error activation woocommerce add-on

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#98]
This from a customer

I deactivated the plugins then activated the Pootle Page Builder, WC Addon and then Storefront Pro.

They activated successfully but broke the URL to my site. Here is the error I get when I now visit my site. www.thehermitcrabpatch.com

Fatal error: Cannot redeclare pp_api_error_info() (previously declared in /home/content/p3pnexwpnas08_data01/65/2858565/html/wp-content/plugins/pb-woocommerce-addon/pp-api/admin/funcs.php:14) in /home/content/p3pnexwpnas08_data01/65/2858565/html/wp-content/plugins/storefront-pro/includes/update-api/admin/funcs.php on line 33

**Comment by shramee** [comment]
This done too ;)
